# Two-pattern DMTS library. Set mouse/device IDs for your actual setup.
experiment_mode: "dmts_patterns"
mouse_id: "332"
device_id: "H2-190"
DMTS stimuli: ["STIM1", "STIM2"]
STIM1: "P1N8 P2N8 P3N8 P1N9 P2N9 P3N9 P1N10 P2N10 P3N10"
STIM1 irradiance (mW/mm2): 2
STIM2: "P8N1 P9N1 P10N1 P8N2 P9N2 P10N2 P8N3 P9N3 P10N3"
STIM2 irradiance (mW/mm2): 2
Pulse duration (ms): 25
Pulse frequency (Hz): 20
Number of pulses: 10
